name: ereborPlugin
version: 1.1
author: Jan-Luca
main: main.MyPlugin
commands:
  wtf:
    description: wtf
  nice:
  ?:
  flyingSpeed:
    description: sets flying Speed
  walkingSpeed:
    description: sets walking speed
  killAll:
    description: kills all Entities except a few non-living ones and players
  inventory:
    description: settings for Inventory bar
  bau:
    description: fill Bereich
  calc:
    description: counts all blocks. use true as first parameter if you want to count air blocks
  wand:
    description: build a wall (insert trump joke here)
    usage: 0 bottom-left. 1 bottom-right. 2 top-right. 3 top-left